# Generated by Django 6.0.3 on 2026-03-30 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('student_id', models.CharField(max_length=20)),
                ('complaint_text', models.TextField()),
                ('routed_to', models.CharField(choices=[('IT', 'IT Department'), ('EXAM', 'Exam Controller'), ('ACCOUNTS', 'Accounts Department'), ('PROVOST', 'Provost Office'), ('ACADEMIC', 'Department Head'), ('STUDENT_AFFAIRS', 'Student Affairs')], max_length=50)),
                ('date_submitted', models.DateTimeField(auto_now_add=True)),
                ('is_resolved', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='lostitem',
            name='contact',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='lostitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='lost_items/'),
        ),
    ]
